#!/bin/bash
set -eu

fields=( $(gem build *.gemspec | grep '\(Version\|File\):' | awk '{print $2}') )
version="${fields[0]}"
gem="${fields[1]}"
[ -n "$version" ] || exit 1
trap "rm -f '$gem'" EXIT

if ! git rev-parse --verify --quiet "refs/tags/v${version}" >/dev/null; then
  git commit -m "ripper-tags $version" -- lib/ripper-tags.rb
  git tag "v${version}"
fi

git push origin HEAD "v${version}"
gem push "$gem"
